name: CI

on: [push]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      - name: MSBuild
        working-directory: percentage
        run: msbuild percentage.sln /property:Configuration=Release
      # - name: Artifact upload
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: percentage
      #     path: percentage\percentage\bin\Release\percentage.exe
  linux-build:
    container:
      image: mono
    steps:
      - name: Prerequisites
        run: sudo apt install -y ssh git bash
      - name: Checkout
        uses: actions/checkout@master
      - name: MSBuild
        working-directory: percentage
        run: msbuild percentage/percentage.sln -p:Configuration=Release
      # - name: Artifact upload
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: percentage
      #     path: percentage\percentage\bin\Release\percentage.exe